apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: cli-job-sa-role
rules:
  - apiGroups:
      - batch
      - tekton.dev
      - apiextensions.k8s.io
    resources:
      - jobs
      - customresourcedefinitions
      - pipelines
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cli-job-sa-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: welcome-pipeline
