bases:
- ../../../components/applications
resources:
- 0.ns.yaml
- 1.secret.yaml
- 2.argocd.yaml
- 3.rbac.yaml
- 4.gt-rollout-rbac.yaml
- 4.gt-rollout-sa.yaml
- 5.gt-rollout-job.yaml
- 6.tekton-rollout-job.yaml
