apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cicd-demo
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/ArmandoTovar/openshift-cicd-demo
      revision: main
      directories:
      - path: tenants/cicd-demo/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/ArmandoTovar/openshift-cicd-demo
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
